language: java

jdk:
  - oraclejdk8

script:
  - ./gradlew clean jekyllBuild

after_script:
  - touch build/_site/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: build/_site/ 
  on:
    branch: master
