# set the theme
theme: unidata-jekyll-theme

# this will appear in an HTML meta tag, sidebar, and perhaps elsewhere
docset_version: 0.3

# this appears on the top navigation bar next to the home button
topnav_title: Rosetta

# this appears in the html browser tab for the site title (seen mostly by search engines, not users)
site_title: Rosetta Documentation

# this appears in the footer
site_topic: Rosetta Documentation

# if you have google-analytics ID, put it in. if not, edit this value to blank.
# e.g. google_analytics: UA-92978945-1
google_analytics: UA-92978945-1

# the preview server used. Leave as is.
host: 127.0.0.1

# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.
port: 4005

# used as a contact email and subject line for the Feedback link in the top navigation bar
feedback_email: support-rosetta@unidata.ucar.edu
feedback_subject_line: Documentation Feedback

# library used for syntax highlighting
highlighter: rouge

# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

# collections are declared here. this renders the content in _tooltips and processes it, but doesn't output it as actual files in the output unless you change output to true
collections:
  tooltips:
    output: false

# these are defaults used for the frontmatter for these file types
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: false
      sidebar: rosetta_sidebar

sidebars:
  - rosetta_sidebar

# project logo (32x32), name, main landing page  (currently used in the footer)
project_logo: https://docs.unidata.ucar.edu/images/logos/rosetta-32x32.png
project_name: rosetta
project_landing_page: https://unidata.ucar.edu/software/rosetta/

# the description is used in the feed.xml file
description: "This is a documentation site for Rosetta, which is part of the THREDDS Project."

# needed for sitemap.xml file only
# must include trailing slash, leave off the version :-)
base_docs_url: https://docs.unidata.ucar.edu/rosetta/