on: [pull_request]

jobs:
  check-dependency-availability:
    name: Check fresh compile and assemble of Roetta project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Build with Gradle (refresh dependencies)
        run: ./gradlew clean classes testClasses assemble --refresh-dependencies
