name: Rosetta CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['1.8']
    name: Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v1
      - name: Set java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          architecture: x64
    - run: ./gradlew clean test integrationTests
