on: [pull_request]

jobs:
  tests-zulu:
    name: Rosetta Tests (Zulu JDK)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against latest 8, 11 LTS versions
        java: [ 8, 11 ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          architecture: x64
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build and test with Gradle
        run: ./gradlew clean test integrationTests
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Rosetta_JUnit_Results_${{ github.sha }}_Zulu-JDK-${{ matrix.java }}
          path: build/reports/allTests

  tests-adpotopenjdk-hs:
    name: Rosetta Tests (AdoptiumJDK-HS)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against latest Adoptium LTS releases, and latest non-LTS version supported by gradle
        java: [ 8, 11, 14 ]
    steps:
      - uses: actions/checkout@v2
      - name: Fetch latest Adoptium JDK ${{ matrix.java }} (hotspot) built for linux
        run: curl -L "https://api.adoptopenjdk.net/v3/binary/latest/${{ matrix.java }}/ga/linux/x64/jdk/hotspot/normal/adoptopenjdk" -o aojdk${{ matrix.java }}-hs.tar.gz
      - name: Setup Latest Adoptium JDK (hotspot) ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          architecture: x64
          jdkFile: ./aojdk${{ matrix.java }}-hs.tar.gz
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-${{ matrix.java }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-${{ matrix.java }}-gradle
      - name: Build and test with Gradle
        run: ./gradlew clean test integrationTests
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Rosetta_JUnit_Results_${{ github.sha }}Adoptium-HS-${{ matrix.java }}
          path: build/reports/allTests
